### ISSUE TITLE
Tooltip problem

### ISSUE THREAD

**Issue by triksterr** [litdev1/SB-IDE#10]
If I create variable names in English, they are prompted with lowercase and uppercase letters. It's OK.

But if I create variable names in Russian, I have a tooltip problem. 
When the variable name starts with a lowercase letter, the tooltip works correctly: when I enter lowercase and uppercase letters. 
But when the name starts with an uppercase letter, the tooltip works only when I enter an uppercase letter.

The same problem exists with the tooltip of objects and functions in Russian (all names starts with an uppercase letter).

**Comment by litdev1** [comment]
Hi,
I cannot fully test this so I am guessing a bit.

Firstly **it is not a good idea to use non-ascii characters in your code** for variable names.  This includes Cyrillic which are not stored as ascii, therefore various string commands internally do not always behave as expected, eg case insensitive comparisons.  Most software languages don't allow this and the fact that Small Basic does is probably an oversight rather than by design - **you can expect strange behaviour sometimes**.  I don't really consider this supportable in general - what about Japanese, Arabic, Klingon etc.

Having given the warning and the fact that I don't really consider this supportable, I have had a go.  You can get my efforts with **Advanced->Update**.

In **Advanced->Options** there is a new option to add additional regex for allowed variable names, where you can add "а-яА-ЯёЁ" for example.

PS. Note that the **only thing** that the additional regex can affect is the list of variable names used for tooltip.

**Comment by triksterr** [comment]
> Firstly it is not a good idea to use non-ascii characters in your code for variable names.

For young Russian children who do not know and do not understand English, Russian classes and variables in the programming language are the exclusive possibility to learn programming.
Therefore, language support is absolutely essential.

> In Advanced->Options there is a new option to add additional regex for allowed variable names, where you can add "а-яА-ЯёЁ" for example.

Ok. I will test it. Thanks!

**Comment by triksterr** [comment]
It works only like this:
When the variable name starts with a lowercase letter, the tooltip works correctly: when I enter lowercase and uppercase letters.
But when the name starts with an uppercase letter, the tooltip works only when I enter an uppercase letter. :(

**Comment by litdev1** [comment]
Not really surprising since the .Net string methods don't all play nice with non ascii characters - it appears that it cannot properly do a string comparison that is case insensitive, perhaps you can test if this is true for all capital characters of just some?

The code is really simple, but just doesn't seem to work in this case, and I can't see what to change?

_if (label.StartsWith(input, StringComparison.OrdinalIgnoreCase))_

**Comment by litdev1** [comment]
I have had a go with _label.ToUpperInvariant().StartsWith(input.ToUpperInvariant())_

Test with Advanced->Update

**Comment by triksterr** [comment]
Yes! It works!
Can you do this for all other elements of the language?

**Comment by litdev1** [comment]
I assume you mean methods etc - I can do the obvious stuff in SB-Prime, I expect much of SB compiler and SmallBasicLibrary.dll and any extension will may not like it, but I may be wrong.  This is a bit of work and hard to guarantee I will catch everything.  I am faily certain that keywords cannot change (For, Sub, EndWhile etc).

**Comment by litdev1** [comment]
This was quite a lot of changes, easy to do (find and Replace stuff) but potentially issues so I have put up test version for download.

[http://litdev.co.uk/downloads/SB-Prime-TEST.zip](http://litdev.co.uk/downloads/SB-Prime-TEST.zip)

The purpose of this test build is not that it fixes everything for the future, more that it hasn't broken what already exists - I will also check - things that might change (find and replace, shapes editor, flow chart, lexer, debugging, extension loading), especially anything that could be case sensitive or case insensitive

**Comment by triksterr** [comment]
Ок. I need time to test it.

**Comment by triksterr** [comment]
Where and what is worth to checking?

**Comment by litdev1** [comment]
I think just run through the main features I listed, do some find and replace case and not sensitive, check the intellisense tooltips, the shapes and flowchart.  I have done it too and looks OK to me.  I wouldn't spend more than 10 min on it - I think its OK, but changing so much stuff by copy/paste is always dangerous so some basic independent testing is good enough
Thanks
