### ISSUE TITLE
Additional functionality

### ISSUE THREAD

**Issue by triksterr** [litdev1/SB-IDE#4]
Hello!

What about help system for this IDE?
What about help and interface translation?
What can you say about small internal preprocessor for text-include of .sb files, for simple macros and for correct function réalisation? Or maybe you can make preprocessor command in IDE settings for external preprocessor?

With best regards.

**Comment by triksterr** [comment]
The sample of function realisation via preprocessor.

Program text before preprocessor:

**Function fname (a, b, c)** _' function definition_
**....** _' code of function on SB_
**Return d** _' the variable that must be returned_
**....
EndFun**


Function call in the text of program (before preprocessor):

**e = fname (x, y, z)**



Program code after preprocessor:

**Sub fname**
**....**  _' code of function (with using convercion variables fname_a, fname_b, fname_c, fname_d)_
**EndSub**


Function call in the text of program (after preprocessor):

**fname_a = x
fname_b = y
fname_c = z
fname()
e = fname_d**

**NB**: Long names of convercion variables - is for "localising" of them.

**Comment by litdev1** [comment]
Hi, 

Function and subroutine arguments are a change to the compiler, not the IDE.  I want code to be compatible with standard Small basic.

There have been many discussions on the SB forum about this.  The main issue that function arguments will remove or at lease confuse (like your localising variable names) global scope that is a fundamental simplification in SB language.  While global scope is a very poor paradim for a software language, it does lower the hurdle to getting started, and when you realise that it is a real limitation you should be trying java, python, C# or some other.

It is possible to use extensions to mimic this behavior, eg. LDCall.Function and others.  There are also some other (non-compatible) versions of small basic compiler that do have function arguments, e.g. [http://www.trelford.com/blog/post/funprocedures.aspx](http://www.trelford.com/blog/post/funprocedures.aspx)

**Comment by triksterr** [comment]
Ok. I understand your position. 
And what about option of connecting external preprocessor in the IDE?
It's simple: it is enough just to define the program interface and command line format for the option string at the Options panel.
This option does not change the SB language, but very useful for many tasks.

And...
What about help system for IDE?
What about help system and IDE interface translation?
How can I copy any text from the Intellisense panel?
And what about simple option "Auto open last project at start"?

**Comment by litdev1** [comment]
**And what about option of connecting external preprocessor in the IDE?
It's simple: it is enough just to define the program interface and command line format for the option string at the Options panel.**
I'm not really clear what this is - I did add the option for anyone to write their own plug-in for SB-Prime so perhaps this is a case for this.

**What about help system for IDE?**
Its pretty straight forward to use really, and to be totally honest I wrote this as a fun project for the SB community in my spare time - nothing to do with MS - and I don't really fancy writing documentation how to use find and replace or what an indent preference might be - sorry.  I did write something for the debugging which is the main reason I wrote SB-Prime.  I also wrote ToolTips for most buttons/options as a guide.

**What about help system and IDE interface translation?**
I don't speak other languages and this is just a fun hobby project - not a commercial software.  However if you set the language code the intellisense is translated if the language translation is available (most languages for standard SB and some for extensions).  I also wrote a project to auto translate extension XML to most languages (TranslateXML).  I can translate any extension XML API and am happy to do it.  [Here](http://litdev.co.uk/#Other%20Resource%20Downloads) are some I did in the past (navigate to the Translation section).

**How can I copy any text from the Intellisense panel?**
You cannot, but all the intellisence is also available in Tools|Search Extensions (SmallBasicLibrary is default methods).  It is also just the same as the standard documentation (comes from the XML supplied with SB or extensions) which is available in many places on the web in printable copy/paste versions.  [Here ](http://litdev.co.uk/#LitDev%20Extension%20Documentation) are some I auto-converted to web pages, but there are many other forms available.

**And what about simple option "Auto open last project at start"?**
Possible, but its so easy to get the last file from taskbar list or the list in File option using system MRU (Most Recently Used) store.

I don't want to be negative and I'm happy to fix bugs, but not generally just add stuff that isn't central to Small Basic - I'm not trying to write Development Studio for Small Basic, just something slightly more powerful than the default SB IDE - mainly the debugger which was what I thought was really missing.

If you want more info on any of the workarounds or alternatives I suggest then the [SB forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=smallbasic) is the best place to ask since it may be helpful to others.

**Comment by triksterr** [comment]
Your project is really grandiose, no matter how hobby it may be. Your IDE and library turn a rather simple and not too convenient programming language into a full-fledged tool for beginning programmers, on which you can not only learn programming, but also write excellent application applications for Windows.

**I'm not really clear what this is - I did add the option for anyone to write their own plug-in for SB-Prime so perhaps this is a case for this.**
Plugins are a great opportunity! Where can I read plugin development docs and how do they work?

I can create a help file in the appropriate language. How can I connect it to IDE?

I can translate the IDE interface, but I need the interface texts for it.

**Comment by litdev1** [comment]
Hi,

There is no way to include IDE translation at present - this would be a largish dev to do this.

This is the info on plugins I put on the [TechNet download site](https://gallery.technet.microsoft.com/Small-Basic-IDE-10-42648328).  You will need to know some C# programming and depending on what you want to do; interact with the code for SB-Prime.  Adding help should be pretty easy since it needs minimal interaction with SB-Prime code.

[Here is a link](https://social.msdn.microsoft.com/Forums/en-US/cc4723d4-884a-4cd5-b604-371e5137dac9/sbide-plugins?forum=smallbasic) where some SB users work on plugins - I recall there are other posts too.

**Plugins**

Plugins may be written for SB-Prime.  A sample VS 2017 project to get you started may be downloaded from [litdev.co.uk/downloads/SBSamplePlugin.zip](litdev.co.uk/downloads/SBSamplePlugin.zip).

A GitHub version of the plugin sample source code is also available from [https://github.com/litdev1/SBSamplePlugin](https://github.com/litdev1/SBSamplePlugin).

Plugin dlls should be unblocked if downloaded, then placed in a subfolder of the SB-Prime.exe location, called 'plugins'.

Using the plugin sample, only the SBSamplePlugin.dll file should be placed in the plugins folder.

The dlls in the plugins folder will be auto detected and loaded to a new ribbon button if they are are correctly created.

**Comment by triksterr** [comment]
OK. Thank You for the info of writing plugins for the IDE.

Can I translate the IDE interface into Russian using Microsoft Visual Studio?

**Comment by litdev1** [comment]
Yes, you could get a copy of the VS solution from here and change the text literals in xaml code for each window and recompile.  If there any version changes you would have to redo, or at least merge the new stuff.  The easiest would be to just change the text, more work would be to use text resources, [like this](https://www.rhyous.com/2010/10/20/using-resources-resx-for-strings-in-a-wpf-application-a-technique-to-prepare-for-localization/).

I'm not an expert on this and there seems to be a difference in how text in the xaml and other text is handled.  The former would need to be compiled for each localisation (at least a different dll) and the latter can be handled by resx files like the main SB IDE.

**Comment by litdev1** [comment]
Hi,
I looked into this a bit more and think I can do different languages fairly easily with text snippets translated.  I may not have got every bit of text but the attached is a list I have so far.

The attached file does it using machine translation - may or may not be any good.

It OK - or you modify it, then I can add it as a resource used depending on the PC language culture (ru) for russian.

[localisation.xlsx](https://github.com/litdev1/SB-IDE/files/4334514/localisation.xlsx)

**Comment by triksterr** [comment]
Is localization in SB-Prime possible using resx files?

**Comment by litdev1** [comment]
Yes - I,ve been playing/learning and got it working I think - my translations are by machine so may be a bit odd but the process works I think - still a little hard to test since my PC is locale en (english).

I would like to test what I have, then perhaps you could scan through the language translaton in excel I gave and fix any really bad ones for me.

So the test version I upload to [http://litdev.co.uk/downloads/SB-Prime-TEST.zip](http://litdev.co.uk/downloads/SB-Prime-TEST.zip).

I thik it should work directly, detecting a ru version of windows, if not try starting from command line with - SB-Prime /lang:ru

Let me know how it goes - cheers.

**Comment by triksterr** [comment]
Excellent! I want to make the latest version of the IDE in Russian. Can I decompile russian SB-Prime.resources.dll file and than edit all Russian phrases and translations?
I can provide the correct Russification of the IDE for everyone too.
Also, I can coordinate the translation of the interface and help for the Russian and Spanish languages.

When is the interface translation planned in SB-Prime release?

It seems to me the most reasonable way to connect the language translation library whith the language prefix specified in the SB-Prime settings.

And what about setting up hot keys for basic operations related to folding structures and commenting on lines specified in the context menu? It is very useful.

**Comment by triksterr** [comment]
The russian translation works nice detecting a ru version of windows. Without problems. And it seems to me the most reasonable way to connect the language translation library whith the language prefix specified in the SB-Prime settings.

**Comment by litdev1** [comment]
It should detect the new resx for the interface from the regional settings on your PC.  The language prefix in the interface is currently completely separate and is only to do with the xml files for intellisense - I intend to leave that as it is at the moment.

The interface can be over-ridden in the test version starting on command line with /lang:ru or /lang:en for example.

I did this with auto language converion by machine.  If the translation is acceptable (doesn't have to be perfect) then I would prefer to do it by machine since it is easy to update in a couple clicks when new bits are added rather than merging - which can be a tedious error prone manual process (not keen).

I did have a few bugs introduced by this so I would like a bit of testing - at least every screen/functonality works before uploading - perhaps you can do a bit.

If folk don't like, then use /lang:en to revert.

Hot-keys I followed the main SB - maybe add some, but remember this is mainly for children starting to learn programming, not an alternative to Visual Studio - its meant to be small and basic.

**Comment by litdev1** [comment]
Before I do work modifying the translations to fix bug raised by Blockguy24, can you confirm that I have the most recent version of the resx, which I can fix.

**Comment by triksterr** [comment]
Can You send me this file via E-mail?

**Comment by litdev1** [comment]
[Strings.zip](https://github.com/litdev1/SB-IDE/files/4439167/Strings.zip)

Ok here is what I have without the @amp corrections.

ps these are exactly what is in this git solution so you can get them also from here, I try to keep stuff updated in git where possible - and sometimes there are bugs, but then they tend to get spotted quickly as we improve stuff.

**Comment by triksterr** [comment]
No!!!

The auto generation destroys original symbols! :( It's a problem.
You can see it inside the Strings.ru.resx file, and in ALL .resx files.


пн, 6 апр. 2020 г. в 18:05, litdev1 <notifications@github.com>:

**Comment by litdev1** [comment]
I know - I was just saying how they got there - the original literals has these extended ascii escape codes for special characters like < and the escape codes were copied to resx when I generated them automatically, but resx handles escape code differently - UTF-8 probably.  Anyway I will fix in all resx and test.

**Comment by triksterr** [comment]
Ok.
I see.
Ok. I'll wait.

пн, 6 апр. 2020 г. в 19:52, litdev1 <notifications@github.com>:
