### ISSUE TITLE
Code "not compiling"

### ISSUE THREAD

**Issue by Blockguy24** [litdev1/SB-IDE#5]
I'm currently having this issue where it says `Compile : Failed to create exe` when attempting to run code.

The `%TEMP%` directory contains randomly named .exe files, which are in fact correctly compiled, contrary to what SB-Prime believes.
After further investigation I found this:
https://github.com/litdev1/SB-IDE/blob/811149b42379d53c9d97841a174c34020834c596/SB-Prime/SBInterop.cs#L536-L541
I'm not exactly sure why the last write time needs to be checked, especially because this code is only reached if `0 errors` is returned by the compiler.

I modified the code to print the result of `Datetime.Now - File.GetLastWriteTime(output)` to the console, and it was about 1700 ms.

If this is to prevent file name collisions, you could test if the output file already exists, delete it, and then run the compiler.

**Comment by litdev1** [comment]
Hi,

This is a good spot.  First, the temp folder is used (as it is with standard SB) for compiling etc when a *.sb file has not yet been saved to a specific location.  It can get get clogged with orphoned files and should be cleaned out every so often.  If everything goues OK temp files are cleaned up, but not always otherwise.

You have correcly found the culprit code.  The logic is a bit convoluted.
1] We compile
2] If there are errors we report them
3] If there are no errors we check that the exe is created within last 1000 ms and this is the problem.  

So why did I do this?

It is possible that the compiler works but cannot over-write a previous exe due to permissions, usually when we are not in the temp folder, but rather some other folder (if the *.sb is saved in another folder the exe is created there).
This is a bit of an edge case, but it did happen during development and the 1 sec test that the exe was actually created by the compilation rather than an old exe that could not be over-written.  I didn't delete the old exe before compilation in case compiler fails and we have lost a previous working exe.

So, clearly the 1 sec test isn't good and I will have a little think on getting all the logic right.  Thanks for reporting.

Fixed.

**Comment by Blockguy24** [comment]
Possibly, the IDE could check the permissions of the compile directory beforehand, either by writing a test file to the directory or by some other method.

**Comment by litdev1** [comment]
To be honest I can't really remember the full reasons for these extra checks, and may have been to fix something at early stages of the debugger development that isn't an issue as it evolved.
Anyhow, I can't see a good reason as it stands and have simplified - and will go with that till someone comes up with a bug/case where it doesn't work.
