### ISSUE TITLE
Broken Text

### ISSUE THREAD

**Issue by Blockguy24** [litdev1/SB-IDE#9]
Some of the text in the interface just isn't displaying correctly.

Example 1:
![image](https://user-images.githubusercontent.com/21016331/78521883-cb113800-780e-11ea-971b-6562ff5347e6.png)

Example 2:
![image](https://user-images.githubusercontent.com/21016331/78521887-cea4bf00-780e-11ea-8f32-52e8d90c3f95.png)

**Comment by litdev1** [comment]
Hi,
Thanks for reporting.  This is part of quite extensive work to add international localisations - please see other issues.  I will fix these, look like due to special characters.

**Comment by triksterr** [comment]
I got this problem in Russian translation. 
I could to solve it by inserting the appropriate characters instead of the code and the problem disappeared. Try to do the same in the English text.

**Comment by triksterr** [comment]
I think You need change these strings:

`"Break if &lt;"` to `"Break if <"`
`"Break if &gt;"` to `"Break if >"`
etc.

In the English Strings.resx file.

**Comment by litdev1** [comment]
@triksterr

Thanks, it was due to auto generation of the strings.  

I know how to fix in resx, I just want to make sure I fix in the most recent versions - which should be those in git.  So if you have versions that are modified with corrected russian or spanish from the most recent (those currently in git) then please send them to me (fixed or not since the fix is easy).  

I will then update resx as neccessary, update git and update the download and we will alll be up to date.

Thanks.

**Comment by triksterr** [comment]
Ok.
Now You have the latest versions.
[Strings.ru.zip](https://github.com/litdev1/SB-IDE/files/4439645/Strings.ru.zip)

**Comment by litdev1** [comment]
Thanks

**Comment by litdev1** [comment]
I have updated, checked into git and uploaded the corrected localisation strings.  The upload is to the main Advanced->Update location (not the TEST location i.e. without any of the debug output currently being used to test localisation issues in the shapes editor).

**Comment by triksterr** [comment]
The problem is solved now - in Russian and English:

![Снимок](https://user-images.githubusercontent.com/48825903/78598479-0c7a0580-7858-11ea-8107-44ee95bde0f9.PNG)

![Снимок2](https://user-images.githubusercontent.com/48825903/78598493-10a62300-7858-11ea-8a2e-cbfd0c527246.PNG)

![Снимок3](https://user-images.githubusercontent.com/48825903/78598505-14d24080-7858-11ea-91a0-72a551a54b3b.PNG)

**Comment by triksterr** [comment]
The problem is solved now - in Russian and English! :)

It;s great!

пн, 6 апр. 2020 г. в 20:12, litdev1 <notifications@github.com>:

**Comment by triksterr** [comment]
> Some of the text in the interface just isn't displaying correctly.

 Can You colse this solved entry?

**Comment by Blockguy24** [comment]
Ok, I'll close this now. Thanks for the fix.
